language:
 - gcc
 - clang
before_install:
 - pip install --user cpp-coveralls --use-mirrors
script:
 - make && make test
after_success:
 - coveralls -v --exclude lib --exclude tests --exclude bencode.h
